TARGET_BIN = libxively_experimental_unit_test_suite

TEST_HEADERS := $(wildcard ../../experimantal/on_demand_processing_prototype/*.h) 
TEST_SOURCES := $(wildcard ../../experimantal/on_demand_processing_prototype/*.c)
TEST_SOURCES += ../../ext/tinytest/tinytest.c

include ../Makefile.helper
